apiVersion: v1
kind: ServiceAccount
metadata:
  name: opas-api
  namespace: opas
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-manager
  namespace: opas
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-manager-binding
  namespace: opas
subjects:
  - kind: ServiceAccount
    name: opas-api
    namespace: opas
roleRef:
  kind: Role
  name: job-manager
  apiGroup: rbac.authorization.k8s.io
